language: cpp

os:
  - linux
  - osx

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt551
      && sudo apt-get -qq update
      && sudo apt-get -qq install -y g++-4.8 libc6-i386 freeglut3-dev qt55tools qt55base qt55translations qt55imageformats
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update > /dev/null
      && brew install homebrew/x11/freeglut
      && brew install qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      QTDIR="/opt/qt55";
    else
      QTDIR="/usr/local/opt/qt5";
    fi
  - PATH="$QTDIR/bin:$PATH"
  - mkdir -p build
  - cd build
  - qmake ..
  - make -j2

env:
  global:
   # COVERITY_SCAN_TOKEN
   - secure: "lk7jEPh62LhXOWyT5UyGAKPxiskVyIBbHEtbnfKZZil2iJLec1f3+df1ADPajl1Ij2Yp4ZgWWcJsuN/+XkQJjXvgWyW2bi0K9ntrRCU4t3h8blodblaXvpssbz5fj4TzI8HnfBet4NXfLLdAUHBcLOLU01xb+LWaY/4rX2PlKBY="

addons:
  coverity_scan:
    project:
      name: "myst6re/makoureactor"
      description: "Final Fantasy VII field archive editor"
    build_command_prepend: "mkdir -p build && cd build && qmake .."
    build_command: "make -j2"
    branch_pattern: coverity_scan
