environment:
  QTDIR: C:\Qt\5.5\msvc2013

install:
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"'
  - curl -L -o upx.zip http://upx.sourceforge.net/download/upx391w.zip &&
    7z e upx.zip *.exe -r

before_build:
  - qmake -config release Makou_Reactor.pro

build_script:
  - jom

after_build:
  - FOR /F %%i IN ('git describe --tags') DO SET GIT_TAG_OR_BRANCH=%%i
  - set DEPLOY_DIR="makoureactor-%GIT_TAG_OR_BRANCH%-win32"
  - echo "%DEPLOY_DIR%"
  - deploy.bat
  - MOVE *.qm deploy
  - DIR deploy
  - MOVE deploy "%DEPLOY_DIR%"
  - 7z a "%DEPLOY_DIR%.zip" "%DEPLOY_DIR%"

artifacts:
  - path: makoureactor-*-win32.zip

deploy:
  description: Description # Mandatory
  provider: GitHub
  auth_token:
    secure: "g4SNxnp5gaEg3KPXOsgEiAW1t1ObzDr+Nm9ZkQBvqpDwM6K5skfUL1FGiBpQeWRiaVYymbY1ukn+rIFH36vJWl1+MK+6YYS4EvLY6o+pgHXzqeiM/NeC4qd2HRzQxDo4T5Ox5tVzTavrDR+fOuo/iMolx/IfnQaJ+m/csTYYdm0="
  artifact: /.*-win32\.zip/
  on:
    appveyor_repo_tag: true # deploy on tag push only
