environment:
  matrix:
    - USE_MSVC: 1
      QTDIR: C:\Qt\5.13\msvc2017
      QTTOOLS: C:\Qt\Tools\QtCreator
    - USE_MINGW: 1
      QTDIR: C:\Qt\5.13\mingw73_32
      QTTOOLS: C:\Qt\Tools\mingw73_32

install:
  - DIR C:\Qt
  - DIR C:\Qt\Tools
  - DIR %QTDIR%
  - DIR %QTTOOLS%
  - set PATH=%QTDIR%\bin;%QTTOOLS%\bin;%PATH%
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"'
  - curl -L -o upx.zip http://upx.sourceforge.net/download/upx391w.zip &&
      7z e upx.zip *.exe -r

before_build:
  - qmake -config release Makou_Reactor.pro

build_script:
  - if "%USE_MSVC%"=="1" jom
  - if "%USE_MINGW%"=="1" mingw32-make

after_build:
  - FOR /F %%i IN ('git describe --tags') DO SET GIT_TAG_OR_BRANCH=%%i
  - if "%USE_MSVC%"=="1" set DEPLOY_DIR="makoureactor-%GIT_TAG_OR_BRANCH%-win32"
  - if "%USE_MINGW%"=="1" set DEPLOY_DIR="makoureactor-%GIT_TAG_OR_BRANCH%-xp"
  - echo "%DEPLOY_DIR%"
  - deploy.bat
  - MOVE *.qm deploy
  - DIR deploy
  - MOVE deploy "%DEPLOY_DIR%"
  - 7z a "%DEPLOY_DIR%.zip" "%DEPLOY_DIR%"

artifacts:
  - path: makoureactor-*.zip

deploy:
  description: Description # Mandatory
  provider: GitHub
  auth_token:
    secure: Q8v2IrepAs+HGD3atYI/0cI52LrxaYzRZKDBaFMSjsz1NPoUrj+Q4lZaZzFaLa4v
  artifact: /makoureactor-.*\.zip/
  on:
    appveyor_repo_tag: true # deploy on tag push only
