environment:
  QTDIR: C:\Qt\5.5\msvc2013

install:
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
  - dir "C:\Program Files"
  - dir "C:\Program Files (x86)"
  - dir "C:\Program Files (x86)\Microsoft Visual Studio 15.0"
  - dir "C:\Program Files (x86)\Microsoft Visual Studio 15.0\VC"
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"'

before_build:
  - qmake Makou_Reactor.pro

build_script:
  - jom -j 2
