environment:
  QTDIR: C:\Qt\5.5\msvc2013

install:
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"'
  - curl -L -o upx.zip http://upx.sourceforge.net/download/upx391w.zip &&
    7z e upx.zip *.exe -r

before_build:
  - qmake -config release Makou_Reactor.pro

build_script:
  - jom

after_build:
  - FOR /F %%i IN ('git describe --tags') DO SET GIT_TAG_OR_BRANCH=%%i
  - DEPLOY_DIR="makoureactor-%GIT_TAG_OR_BRANCH%-win32"
  - echo "%DEPLOY_DIR%"
  - deploy.bat
  - MOVE *.qm deploy
  - DIR deploy
  - MOVE deploy "%DEPLOY_DIR%"
  - 7z a "%DEPLOY_DIR%.zip" "%DEPLOY_DIR%"

artifacts:
  - path: makoureactor-*-win32.zip
